# Generated by Django 3.1.6 on 2021-02-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100, null=True)),
                ('modified_time', models.CharField(default='02/10/2021 05:44:12 PM', max_length=50)),
                ('blocked', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=10000, null=True)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='usersx.User')),
            ],
        ),
    ]
