# Generated by Django 3.1.6 on 2021-02-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersx', '0002_auto_20210210_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modified_time',
            field=models.CharField(default='02/10/2021 06:05:41 PM', max_length=50),
        ),
    ]
