# Generated by Django 3.1.6 on 2021-02-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersx', '0004_auto_20210210_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_time',
            field=models.CharField(default='02/10/2021 07:35:26 PM', max_length=50),
        ),
    ]
