# Generated by Django 3.1.6 on 2021-02-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersx', '0008_auto_20210211_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modified_time',
            field=models.CharField(default='02/11/2021 07:10:26 PM', max_length=40),
        ),
    ]
